# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: El Cuento
email: jd.decoi@jd.com
description: > # this means to ignore newlines until "baseurl:"
  En mi granja habia un cerdo que se llamaba bingo, B-I-N-G-O, B-I-N-G-O, B-I-N-G-O
  que se llamaba BIIIIIINGOOOOO  (O perro me da igual)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: decoi_LVS
github_username:  Decoi

# Build settings
markdown: kramdown
